import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ScrollToTop from "@/components/ScrollToTop";
import { ThemeProvider } from 'next-themes'

import "node_modules/react-modal-video/css/modal-video.css";
import '../styles/index.css'
 
export default function MyApp({ Component, pageProps }) {
    return (
        <html suppressHydrationWarning lang="en">
            <title>Free Next.js Template for Startup and SaaS</title>
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/images/favicon.ico" />
    
            <body className="dark:bg-black">
                <ThemeProvider attribute="class" enableSystem={false} defaultTheme="dark">
                    <Header />
                    <Component {...pageProps} />
                    <Footer />
                    <ScrollToTop />
                </ThemeProvider>
            </body>
        </html>
    )
}
